version: '2'
networks:
  trillian: {}
services:
  etcd:
    image: quay.io/coreos/etcd:v3.1.7
    command: /usr/local/bin/etcd -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379
    networks:
      - trillian
    ports:
      - "2379:2379"
      - "4001:4001"
  db:
    build: db/
    image: db:db
    networks:
      - trillian
  log_signer:
    build: log_signer
    image: log_signer:log_signer
    networks:
      - trillian
    ports:
      - "8092:8092"
    volumes:
      - ./config:/config
    depends_on:
      - db
      - etcd
  log_server:
    build: log_server
    image: log_server:log_server
    networks:
      - trillian
    ports:
      - "8090:8090"
      - "8091:8091"
    volumes:
      - ./config:/config
    depends_on:
      - db
  ct_server:
    build: ct_server
    ports:
      - "6962:6962"
    image: ct_server:ct_server
    networks:
      - trillian
    volumes:
      - ./config:/config
    depends_on:
      - log_signer
      - log_server
